import { useEffect, useMemo, useRef, useState } from 'react';
import type { FormEvent, PointerEvent } from 'react';
import { AnimatePresence, motion, useMotionValue, animate } from 'framer-motion';
import { BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Home, Plus, RotateCcw, Sparkles, Undo2 } from 'lucide-react';

export interface Task { id: string; title: string; date: string; time: string; completed: boolean; createdAt: string; completedAt: string | null; }
type Tab = 'week' | 'stats' | 'add';
const STORAGE_KEY = 'homeflow.tasks.v1';
const WEEKDAYS = ['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'];
const pad = (n:number) => String(n).padStart(2,'0');
const keyOf = (d:Date) => `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const fromKey = (s:string) => { const [y,m,d]=s.split('-').map(Number); return new Date(y,m-1,d); };
const startWeek = (input:Date) => { const d=new Date(input.getFullYear(),input.getMonth(),input.getDate()); const day=d.getDay()||7; d.setDate(d.getDate()-day+1); return d; };
const addDays = (d:Date,n:number) => { const x=new Date(d); x.setDate(x.getDate()+n); return x; };
const weekDays = (anchor:Date) => Array.from({length:7},(_,i)=>addDays(anchor,i));
const dateLabel = (s:string) => fromKey(s).toLocaleDateString('ru-RU',{day:'numeric',month:'long'});
const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const seed = ():Task[] => { const now=new Date(); const today=keyOf(now); return [
  ['Убрать кухню','18:30'],['Вынести мусор','20:00'],['Запустить стирку','21:15']
].map(([title,time],i)=>({id:`dev-${i}`,title,date:today,time,completed:false,createdAt:now.toISOString(),completedAt:null})); };
function loadTasks():Task[]{ try { const raw=localStorage.getItem(STORAGE_KEY); if(raw) return JSON.parse(raw) as Task[]; const initial=import.meta.env.DEV?seed():[]; localStorage.setItem(STORAGE_KEY,JSON.stringify(initial)); return initial; } catch { return []; } }
function saveTasks(tasks:Task[]){ localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks)); }
function useTasks(){
  const [tasks,setTasks]=useState<Task[]>(loadTasks);
  useEffect(()=>saveTasks(tasks),[tasks]);
  const create=(data:Pick<Task,'title'|'date'|'time'>)=>{ const task:Task={...data,id:uid(),completed:false,createdAt:new Date().toISOString(),completedAt:null}; setTasks(v=>[...v,task]); return task; };
  const toggle=(id:string)=>setTasks(v=>v.map(t=>t.id===id?{...t,completed:!t.completed,completedAt:t.completed?null:new Date().toISOString()}:t));
  const update=(id:string,patch:Partial<Task>)=>setTasks(v=>v.map(t=>t.id===id?{...t,...patch}:t));
  const remove=(id:string)=>setTasks(v=>v.filter(t=>t.id!==id));
  return {tasks,create,toggle,update,remove};
}
function stats(tasks:Task[], days:Date[]){ const keys=days.map(keyOf); const week=tasks.filter(t=>keys.includes(t.date)); const completed=week.filter(t=>t.completed).length; const total=week.length; const pct=total?Math.round(completed/total*100):0; const bars=days.map(d=>{const k=keyOf(d), all=week.filter(t=>t.date===k), done=all.filter(t=>t.completed).length; return {all:all.length,done:done,rate:all.length?done/all.length*100:0};}); const allDays=[...new Set(tasks.filter(t=>t.completed).map(t=>t.date))].sort(); let streak=0,longest=0,current=keyOf(new Date()); for(let i=0;i<3650;i++){const k=keyOf(addDays(fromKey(current),-i));if(allDays.includes(k))streak++;else break;} let run=0; for(let i=0;i<allDays.length;i++){ if(i===0||keyOf(addDays(fromKey(allDays[i-1]),1))===allDays[i])run++;else run=1; longest=Math.max(longest,run); } return {week,completed,total,pct,bars,streak,longest}; }

function BottomNav({tab,onChange}:{tab:Tab;onChange:(t:Tab)=>void}){ return <nav className="bottom-nav" aria-label="Основная навигация">{([['week','Неделя',CalendarDays],['stats','Статистика',BarChart3],['add','Добавить',Plus]] as const).map(([id,label,Icon])=><button key={id} className={`nav-item ${tab===id?'active':''}`} aria-label={label} aria-current={tab===id?'page':undefined} onClick={()=>onChange(id)}><span className="nav-pill">{tab===id&&<motion.span layoutId="nav-highlight" className="nav-highlight"/>}<Icon size={20}/></span><span>{label}</span></button>)}</nav> }
function WeekSelector({anchor,selected,onSelect,onShift}:{anchor:Date;selected:string;onSelect:(s:string)=>void;onShift:(n:number)=>void}){ const days=weekDays(anchor); return <div className="week-wrap"><button className="icon-btn" onClick={()=>onShift(-1)} aria-label="Предыдущая неделя"><ChevronLeft/></button><div className="week-selector" role="tablist" aria-label="Выбор дня">{days.map(d=>{const k=keyOf(d), active=k===selected, today=k===keyOf(new Date());return <button key={k} role="tab" aria-selected={active} className={`day-pill ${active?'selected':''}`} onClick={()=>onSelect(k)}>{active&&<motion.span layoutId="day-highlight" className="day-highlight"/>}<span className="day-name">{WEEKDAYS[d.getDay()===0?6:d.getDay()-1]}</span><strong>{d.getDate()}</strong>{today&&<i/>}</button>})}</div><button className="icon-btn" onClick={()=>onShift(1)} aria-label="Следующая неделя"><ChevronRight/></button></div> }
function SwipeTask({task,onToggle}:{task:Task;onToggle:(id:string)=>void}){ const x=useMotionValue(0), start=useRef({x:0,y:0}), decided=useRef(false), [dragging,setDragging]=useState(false); const onDown=(e:PointerEvent)=>{ if(e.pointerType==='mouse'&&e.button!==0)return; start.current={x:e.clientX,y:e.clientY}; decided.current=false; setDragging(true); (e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId); }; const onMove=(e:PointerEvent)=>{if(!dragging)return; const dx=e.clientX-start.current.x,dy=e.clientY-start.current.y;if(!decided.current&&Math.abs(dx)<8&&Math.abs(dy)<8)return; if(!decided.current){decided.current=Math.abs(dx)>Math.abs(dy); if(!decided.current)return;} if(decided.current){e.preventDefault();const limit=window.innerWidth*.86;x.set(task.completed?Math.max(-limit,Math.min(dx,0)):Math.max(0,Math.min(dx,limit)));}}; const onUp=()=>{if(!dragging)return;setDragging(false);const threshold=Math.min(window.innerWidth*.7,520), value=x.get(); if((!task.completed&&value>=threshold)||(task.completed&&value<=-threshold)){animate(x,task.completed?-window.innerWidth*.95:window.innerWidth*.95,{type:'spring',stiffness:280,damping:28}).then(()=>{onToggle(task.id);x.set(0);});}else animate(x,0,{type:'spring',stiffness:500,damping:35});}; const progress=Math.min(1,Math.abs(x.get())/(Math.min(window.innerWidth*.7,520))); return <div className="swipe-shell"><motion.div className={`swipe-bg ${task.completed?'undo-bg':''}`} style={{opacity:progress}}>{task.completed?<Undo2/>:<Check/>}</motion.div><motion.article className={`task-card ${task.completed?'completed':''}`} style={{x,touchAction:'pan-y'}} onPointerDown={onDown} onPointerMove={onMove} onPointerUp={onUp} onPointerCancel={onUp} role="button" tabIndex={0} aria-label={`${task.title}, ${task.time}${task.completed?', выполнено, свайп влево для возврата':', активная задача, свайп вправо для выполнения'}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onToggle(task.id)}}}><div className="task-main"><span className="task-dot">{task.completed?<Check size={15}/>:null}</span><div><h3>{task.title}</h3><p><Clock3 size={14}/>{task.time}</p></div></div><ChevronRight className="task-arrow"/></motion.article></div> }
function WeekPage({tasks,anchor,selected,setSelected,setAnchor,onToggle,onAdd}:{tasks:Task[];anchor:Date;selected:string;setSelected:(s:string)=>void;setAnchor:(d:Date)=>void;onToggle:(id:string)=>void;onAdd:()=>void}){ const dayTasks=tasks.filter(t=>t.date===selected).sort((a,b)=>a.time.localeCompare(b.time)); const selectedDate=fromKey(selected); const shift=(n:number)=>{const next=addDays(anchor,n*7);setAnchor(next);setSelected(keyOf(addDays(next,selectedDate.getDay()===0?6:selectedDate.getDay()-1)));}; const done=dayTasks.filter(t=>t.completed).length; return <main><header className="top"><div><span className="eyebrow">HOMEFLOW</span><h1>{selected===keyOf(new Date())?'Сегодня':selectedDate.toLocaleDateString('ru-RU',{weekday:'long'})}</h1><p>{dateLabel(selected)} · {done}/{dayTasks.length} выполнено</p></div><div className="date-orb"><Home size={20}/></div></header><WeekSelector anchor={anchor} selected={selected} onSelect={setSelected} onShift={shift}/><section className="section-head"><div><span className="eyebrow">ПЛАН</span><h2>Домашние дела</h2></div><span className="count-pill">{dayTasks.length}</span></section><AnimatePresence mode="popLayout"><div className="task-list">{dayTasks.length?dayTasks.map(t=><motion.div key={t.id} layout initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,x:40}} transition={{type:'spring',stiffness:420,damping:32}}><SwipeTask task={t} onToggle={onToggle}/></motion.div>):<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="empty"><div className="empty-icon"><Sparkles/></div><h3>Сегодня свободно</h3><p>На этот день задач нет.</p><button className="secondary-btn" onClick={onAdd}><Plus size={17}/>Добавить дело</button></motion.div>}</div></AnimatePresence></main> }
function Progress({value}:{value:number}){return <div className="progress"><motion.div initial={{width:0}} animate={{width:`${value}%`}} transition={{type:'spring',stiffness:80,damping:18}}/></div>}
function StatisticsPage({tasks,anchor}:{tasks:Task[];anchor:Date}){ const s=stats(tasks,weekDays(anchor)); return <main><header className="top"><div><span className="eyebrow">АНАЛИТИКА</span><h1>Статистика</h1><p>Текущая неделя</p></div><div className="date-orb"><BarChart3 size={20}/></div></header><div className="stat-grid"><div className="stat-card"><span>Выполнено</span><strong>{s.completed}</strong><small>за неделю</small></div><div className="stat-card"><span>Не выполнено</span><strong>{s.total-s.completed}</strong><small>за неделю</small></div></div><section className="feature-card"><div className="feature-top"><div><span className="eyebrow">ВЫПОЛНЕНИЕ</span><h2>{s.pct}%</h2></div><span className="muted">{s.completed} из {s.total}</span></div><Progress value={s.pct}/></section><section className="chart-card"><div className="section-head compact"><div><span className="eyebrow">ПО ДНЯМ</span><h2>Прогресс недели</h2></div></div><div className="chart">{s.bars.map((b,i)=><div className="bar-col" key={i}><div className="bar-track"><motion.div className="bar" initial={{height:0}} animate={{height:`${b.rate}%`}} transition={{delay:i*.04,type:'spring',stiffness:120,damping:18}}/></div><span>{WEEKDAYS[i]}</span></div>)}</div></section><div className="mini-stats"><div><span>Streak</span><strong>{s.streak}</strong><small>дней подряд</small></div><div><span>Лучший streak</span><strong>{s.longest}</strong><small>дней подряд</small></div><div><span>Всего</span><strong>{tasks.length}</strong><small>задач</small></div></div></main> }
function AddTaskPage({onCreate}:{onCreate:(d:Pick<Task,'title'|'date'|'time'>)=>void}){ const now=new Date(), [title,setTitle]=useState(''), [date,setDate]=useState(keyOf(now)), [time,setTime]=useState(`${pad(now.getHours())}:${pad(now.getMinutes())}`), [error,setError]=useState(''); const quick=(n:number)=>setDate(keyOf(addDays(new Date(),n))); const submit=(e:FormEvent)=>{e.preventDefault();const clean=title.trim();if(!clean){setError('Введите название дела');return;}onCreate({title:clean,date,time});}; return <main><header className="top"><div><span className="eyebrow">НОВОЕ ДЕЛО</span><h1>Добавить</h1><p>Одно действие — и оно в плане.</p></div><div className="date-orb"><Plus size={20}/></div></header><form className="add-form" onSubmit={submit}><label>Название<input autoFocus value={title} onChange={e=>{setTitle(e.target.value);setError('')}} placeholder="Например, убрать кухню" maxLength={100}/></label><div className="quick-dates">{[['Сегодня',0],['Завтра',1],['Послезавтра',2]].map(([label,n])=><button type="button" key={label} className={date===keyOf(addDays(new Date(),Number(n)))?'quick active':'quick'} onClick={()=>quick(Number(n))}>{label}</button>)}</div><label>Дата<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Время<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-btn" type="submit"><Plus size={19}/>Добавить дело</button></form></main> }

export default function App(){ const {tasks,create,toggle}=useTasks(); const today=useMemo(()=>new Date(),[]); const [tab,setTab]=useState<Tab>('week'), [selected,setSelected]=useState(keyOf(today)), [anchor,setAnchor]=useState(startWeek(today)), [toast,setToast]=useState<string|null>(null); useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(null),1800);return()=>clearTimeout(id)},[toast]); const createTask=(data:Pick<Task,'title'|'date'|'time'>)=>{create(data);setSelected(data.date);setAnchor(startWeek(fromKey(data.date)));setTab('week');setToast('Дело добавлено');}; const handleToggle=(id:string)=>{const t=tasks.find(x=>x.id===id);toggle(id);setToast(t?.completed?'Дело возвращено':'Дело выполнено');}; return <div className="app-shell"><div className="app-content"><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:.18}}>{tab==='week'&&<WeekPage tasks={tasks} anchor={anchor} selected={selected} setSelected={setSelected} setAnchor={setAnchor} onToggle={handleToggle} onAdd={()=>setTab('add')}/>} {tab==='stats'&&<StatisticsPage tasks={tasks} anchor={anchor}/>} {tab==='add'&&<AddTaskPage onCreate={createTask}/>}</motion.div></AnimatePresence></div><BottomNav tab={tab} onChange={setTab}/><AnimatePresence>{toast&&<motion.div className="toast" initial={{opacity:0,y:16,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10,scale:.96}}><Check size={16}/>{toast}</motion.div>}</AnimatePresence></div> }
